fix: Remove --no-pivot flag (not supported by this buildah version)
Error: unknown flag: --no-pivot

This buildah version doesn't support --no-pivot.
Keeping other fixes:
- storage.conf with ignore_chown_errors
- BUILDAH_ISOLATION=chroot
- --userns=host