fix(pipeline): Remove pip cache purge when using --no-cache-dir
Error: 'pip cache commands can not function since cache is disabled'
Solution: Remove 'pip cache purge' since we're already using --no-cache-dir